version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i
      # - npm run lint
  pre_build:
    commands:
      - npm i
      - npm run test
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"